TARGET	= libmatmult.so
LIBSRCS	=
LIBOBJS	= matmult_lib.o matmult_nat.o \
          matmult_kmn.o matmult_knm.o \
          matmult_mkn.o matmult_mnk.o \
          matmult_nkm.o matmult_nmk.o \
          matmult_blk.o

OPT	= -g -fast -xrestrict=%all 
PIC	= -fPIC

CC	= suncc
CFLAGS= $(OPT) $(PIC) $(XOPTS)

SOFLAGS = -shared
XLIBS	= -L/usr/lib64/atlas -lcblas

$(TARGET): $(LIBOBJS)
	$(CC) -o $@ $(SOFLAGS) $(LIBOBJS) $(XLIBS)

clean:
	@/bin/rm -f core core.* $(LIBOBJS) $(TARGET)
