TARGET	= 2_gauss
LIBSRCS	=
LIBOBJS	= main.o gauss.o

OPT	= -g -xopenmp
PIC	=

CC	= suncc
CFLAGS= $(OPT) $(PIC) $(XOPTS)

XLIBS	= -lm

$(TARGET): $(LIBOBJS)
	$(CC) -o $@ $(CFLAGS) $(LIBOBJS) $(XLIBS)

clean:
	@/bin/rm -f core core.* $(LIBOBJS)
